import { useEffect, useState } from 'react'
import Head from 'next/head'
import axios from 'axios'
import Image from 'next/image'
export default function Home() {
  const [image, setImage]= useState(null);
  const [altText, setAltText]= useState('');
  const [images, setImages]= useState(null);
  const [updated, setUpdated] =useState(false);

  useEffect(() =>{
    const config ={
      headers:{
        'Accept': 'application/json',
      }
    };
    const fetchData= async()=>{
      try{
        const res =await axios.get('http://localhost:8000/api/image/retrive-images', config);
        if(res.status === 200){
          setImages(res.data.images);
        }
      }catch(err){

      }
    };
    fetchData();

  }, [updated]);
  const onFileChange = e => setImage(e.target.files[0]);
  const onTextChange = e => setAltText(e.target.value);
  const onSubmit = async e =>{
    e.preventDefault();
    const config = {
      headers:{
        'Accept':'application/json',
        'Content-Type':'multipart/form-data',
      }
    };
    const formData = new FormData();
    formData.append('image', image);
    formData.append('alt_text', altText);

    const body = formData;
    try{
      const res = await axios.post('http://localhost:8000/api/image/upload', body, config);
      if (res.status ===201){
        setUpdated(!updated);

      }
    } catch(err){
      
    }

  };
  return (
    <div>
      <Head>
        <title>Next Js Img Upload</title>
        <meta name="description" content="Generated by create next app" />
        <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi' crossOrigin='anonymous'/>
      </Head>

      
        
        <div className='mt-5 '>
          <h1 className='display-4 mt-5 mb-5 ' >Image Upload app</h1>
          <div className='row'>
            <div className='col-5'>
                <form onSubmit={onSubmit}>
                  <div className='form-group'>
                    <label className='form-label' htmlFor='image'>Image Upload</label>
                    <input className='form-control' 
                    type='file' 
                    name='image' 
                    onChange={onFileChange} 
                    required/>
                  </div>
                  <div className='form-group mt-3'>
                    <label className='form-label' htmlFor='alt_text'>Alt Text</label>
                    <input className='form-control' 
                    type='text' 
                    name='alt_text' 
                    onChange={onTextChange} 
                    required
                    value={ altText}
                    />
                  </div>
                  <button className='btn btn-success mt-3' type='submit'>
                    upload Image
                  </button>
                </form>
            </div>
            <div className='offset-1 col-6'>
                  <h3 className='mb-5'>Images in my database</h3>
                  {
                    images !== null && images.map((image, index) => (
                      <div className='mt-3 mb-3' key={index}>
                      <Image
                        src={`http://localhost:8000${image.image}`}
                        alt={image.alt_text}
                        width={200}
                        height={150}
                      />
                      </div>
                    ))
                  }
            </div>

          </div>

        </div>
         
    </div>
  )
}

